#端口号
server:
  port: 80
#  thymeleaf配置
spring:
  thymeleaf:
    cache: false
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    suffix: .html
    prefix: classpath:/templates/
#h2
  h2:
    console:
      path: /h2
      enabled: true
#JPA
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:~/test4;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
#spring.datasource.driver-class-name: com.mysql.jdbc.Driver
